
package com.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeImpl", targetNamespace = "http://employee.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getNameReturn", targetNamespace = "http://employee.com")
    @RequestWrapper(localName = "getName", targetNamespace = "http://employee.com", className = "com.employee.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://employee.com", className = "com.employee.GetNameResponse")
    public String getName();

    /**
     * 
     * @param name
     */
    @WebMethod
    @RequestWrapper(localName = "setName", targetNamespace = "http://employee.com", className = "com.employee.SetName")
    @ResponseWrapper(localName = "setNameResponse", targetNamespace = "http://employee.com", className = "com.employee.SetNameResponse")
    public void setName(
        @WebParam(name = "name", targetNamespace = "http://employee.com")
        String name);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getIdReturn", targetNamespace = "http://employee.com")
    @RequestWrapper(localName = "getId", targetNamespace = "http://employee.com", className = "com.employee.GetId")
    @ResponseWrapper(localName = "getIdResponse", targetNamespace = "http://employee.com", className = "com.employee.GetIdResponse")
    public String getId();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getAddressReturn", targetNamespace = "http://employee.com")
    @RequestWrapper(localName = "getAddress", targetNamespace = "http://employee.com", className = "com.employee.GetAddress")
    @ResponseWrapper(localName = "getAddressResponse", targetNamespace = "http://employee.com", className = "com.employee.GetAddressResponse")
    public String getAddress();

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "setId", targetNamespace = "http://employee.com", className = "com.employee.SetId")
    @ResponseWrapper(localName = "setIdResponse", targetNamespace = "http://employee.com", className = "com.employee.SetIdResponse")
    public void setId(
        @WebParam(name = "id", targetNamespace = "http://employee.com")
        String id);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "getAgeReturn", targetNamespace = "http://employee.com")
    @RequestWrapper(localName = "getAge", targetNamespace = "http://employee.com", className = "com.employee.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://employee.com", className = "com.employee.GetAgeResponse")
    public int getAge();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getEmailReturn", targetNamespace = "http://employee.com")
    @RequestWrapper(localName = "getEmail", targetNamespace = "http://employee.com", className = "com.employee.GetEmail")
    @ResponseWrapper(localName = "getEmailResponse", targetNamespace = "http://employee.com", className = "com.employee.GetEmailResponse")
    public String getEmail();

    /**
     * 
     * @param address
     */
    @WebMethod
    @RequestWrapper(localName = "setAddress", targetNamespace = "http://employee.com", className = "com.employee.SetAddress")
    @ResponseWrapper(localName = "setAddressResponse", targetNamespace = "http://employee.com", className = "com.employee.SetAddressResponse")
    public void setAddress(
        @WebParam(name = "address", targetNamespace = "http://employee.com")
        String address);

    /**
     * 
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "setEmail", targetNamespace = "http://employee.com", className = "com.employee.SetEmail")
    @ResponseWrapper(localName = "setEmailResponse", targetNamespace = "http://employee.com", className = "com.employee.SetEmailResponse")
    public void setEmail(
        @WebParam(name = "email", targetNamespace = "http://employee.com")
        String email);

    /**
     * 
     * @param age
     */
    @WebMethod
    @RequestWrapper(localName = "setAge", targetNamespace = "http://employee.com", className = "com.employee.SetAge")
    @ResponseWrapper(localName = "setAgeResponse", targetNamespace = "http://employee.com", className = "com.employee.SetAgeResponse")
    public void setAge(
        @WebParam(name = "age", targetNamespace = "http://employee.com")
        int age);

}
